development:
      host: localhost
      adapter: mysql
      database: test
      encoding: utf8
      port: 3306
      username: root
      password: san
     
test: &test
      host: localhost
      adapter: mysql
      database: test
      encoding: utf8
      port: 3306
      username: root
      password: san

production:
      host: localhost
      adapter: mysql
      database: test
      encoding: utf8
      port: 3306
      username: root
      password: san
cucumber:
  <<: *test
